#!/usr/bin/env python3
"""Generates the checks of the uninstall test from the code of the datapack, so nobody has to keep a list.

Usage: gen-uninstall-check.py <repo root> <folder of the test datapack in the world, the one that contains data/>

Writes <folder>/data/timber_test/function/generated/uninstall_objectives.mcfunction:
- one check per scoreboard objective (triggers are objectives) that any function of the datapack creates with
  "scoreboard objectives add": after timber:uninstall the objective must not exist any more. A new objective that is added
  to init and forgotten in uninstall makes the test fail, with its name.
- a TIMBER-WARNING line for everything that can't be looked at from a function, but that uninstall should clean up too:
  scheduled functions (schedule function) and storages, compared with the schedule clear / data remove storage of uninstall.
"""
import os
import re
import sys

repo, dest = sys.argv[1], sys.argv[2]

# 121/ holds the overlay of the newest pack format, both are scanned
folders = [os.path.join(repo, "data", "timber", "function"), os.path.join(repo, "121", "data", "timber", "function")]
uninstall_text = ""
objectives, schedules, storages = set(), set(), set()
for folder in folders:
    for root, _, files in os.walk(folder):
        for name in files:
            if not name.endswith(".mcfunction"):
                continue
            path = os.path.join(root, name)
            text = open(path, encoding="utf-8", errors="replace").read()
            if os.path.relpath(path, folder).replace(os.sep, "/") == "uninstall.mcfunction":
                uninstall_text += text + "\n"
                continue
            objectives.update(re.findall(r"scoreboard objectives add (\S+)", text))
            schedules.update(re.findall(r"schedule function (timber:[\w/]+)", text))
            storages.update(re.findall(r"storage (timber:\w+)", text))

if not objectives:
    sys.exit("gen-uninstall-check: no 'scoreboard objectives add' found in " + str(folders) + ", is the path right?")

lines = [
    "#> GENERATED by .github/scripts/gen-uninstall-check.py from the code of the datapack, do not edit.",
    "#> Checks that no scoreboard or trigger of the datapack exists after timber:uninstall.",
    "scoreboard objectives add timber_test dummy",
    "scoreboard players set #left timber_test 0",
    "data modify storage timber_test:uninstall left set value []",
]
for name in sorted(objectives):
    # adding 0 to a holder works when the objective exists and fails when it doesn't.
    # The names go into a list, a fail in the loop would end this function at the first one.
    lines += [
        f"execute store success score #exists timber_test run scoreboard players add #uninstall_probe {name} 0",
        f'execute if score #exists timber_test matches 1 run data modify storage timber_test:uninstall left append value "{name}"',
        f"execute if score #exists timber_test matches 1 run say TIMBER-ERROR uninstall: the scoreboard {name} still exists",
        f"execute if score #exists timber_test matches 1 run scoreboard players add #left timber_test 1",
        f"execute if score #exists timber_test matches 1 run scoreboard players reset #uninstall_probe {name}",
    ]

cleared_schedules = set(re.findall(r"schedule clear (timber:[\w/]+)", uninstall_text))
for target in sorted(schedules - cleared_schedules):
    lines.append(f"say TIMBER-WARNING uninstall: {target} is scheduled somewhere but uninstall doesn't clear it (schedule clear)")
removed_storages = set(re.findall(r"data remove storage (timber:\w+)", uninstall_text))
for target in sorted(storages - removed_storages):
    lines.append(f"say TIMBER-WARNING uninstall: storage {target} is used but uninstall doesn't remove it (data remove storage)")

lines.append('execute unless score #left timber_test matches 0 run fail [{"text":"still exist after uninstall: "},{"nbt":"left","storage":"timber_test:uninstall"}]')
# (no assert after the fail: it would replace the message with "Expected #left ...", without the names)

out = os.path.join(dest, "data", "timber_test", "function", "generated")
os.makedirs(out, exist_ok=True)
with open(os.path.join(out, "uninstall_objectives.mcfunction"), "w", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"gen-uninstall-check: {len(objectives)} objectives, {len(schedules - cleared_schedules)} schedules and "
      f"{len(storages - removed_storages)} storages that uninstall leaves")
