#!/usr/bin/env python3
"""Generates one autoplant test per block a sapling can be planted on, so a block that is added to (or dropped from) Minecraft is
covered without anybody keeping a list.

Usage: gen-sapling-ground-tests.py <server folder with the downloaded vanilla jar> <folder of the test datapack in the world, the one that contains data/>

The blocks are the resolved tag #minecraft:supports_vegetation of the vanilla server jar, the tag the game itself asks when a sapling is planted.
Writes data/timber_test/test/generated/plant_sapling_on_<block>.mcfunction. Fails when the tag is not found, so a rename can't leave a test that checks nothing.
"""
import glob
import io
import json
import os
import sys
import zipfile

server, dest = sys.argv[1], sys.argv[2]
TAG = "supports_vegetation"

jars = sorted(glob.glob(os.path.join(server, "versions", "*", "server-*.jar")))
if not jars:
    sys.exit("gen-sapling-ground-tests: no vanilla server jar in " + server + "/versions")
z = zipfile.ZipFile(jars[-1])
# the vanilla server jar is a bundler, the game itself is a jar inside of it
for n in z.namelist():
    if n.startswith("META-INF/versions/") and n.endswith(".jar"):
        z = zipfile.ZipFile(io.BytesIO(z.read(n)))
        break


def resolve(tag, seen=()):
    if tag in seen:
        return set()
    entries = json.loads(z.read(f"data/minecraft/tags/block/{tag}.json"))["values"]
    blocks = set()
    for entry in entries:
        entry = entry["id"] if isinstance(entry, dict) else entry
        if entry.startswith("#minecraft:"):
            blocks |= resolve(entry[len("#minecraft:"):], seen + (tag,))
        else:
            blocks.add(entry)
    return blocks


try:
    blocks = sorted(resolve(TAG))
except KeyError:
    sys.exit(f"gen-sapling-ground-tests: block tag #minecraft:{TAG} not found in {jars[-1]}")
if not blocks:
    sys.exit(f"gen-sapling-ground-tests: #minecraft:{TAG} is empty")

out = os.path.join(dest, "data", "timber_test", "test", "generated")
os.makedirs(out, exist_ok=True)
for block in blocks:
    name = block.split(":")[1]
    with open(os.path.join(out, f"plant_sapling_on_{name}.mcfunction"), "w", newline="\n") as f:
        f.write(f"""#> GENERATED by .github/scripts/gen-sapling-ground-tests.py, do not edit. With plant_sapling on, a sapling item that lies on {block} gets planted
# @environment timber_test:plant_sapling_on
# @template timber_test:arena
# @timeout 400
# @skyaccess true

function timber_test:platform
setblock ~10 ~-1 ~10 {block}
summon minecraft:item ~10.5 ~0.5 ~10.5 {{Item:{{id:"minecraft:oak_sapling",count:1}}}}

# the loop runs every 2 seconds
await block ~10 ~ ~10 minecraft:oak_sapling
""")
print(f"gen-sapling-ground-tests: {len(blocks)} blocks: {', '.join(b.split(':')[1] for b in blocks)}")
