#!/usr/bin/env python3
"""Generates the checks of the uninstall test from the code of the datapack, so nobody has to keep a list.

Usage: gen-uninstall-check.py <repo root> <folder of the test datapack in the world, the one that contains data/>

Writes two functions into <folder>/data/timber_test/function/generated/:
- uninstall_prepare: puts something into every storage key the datapack writes to, so that the removal is something to check.
- uninstall_objectives: runs after timber:uninstall and FAILS, with the names, if something of the datapack is left:
  * a scoreboard objective (triggers are objectives) that any function creates with "scoreboard objectives add"
  * a storage key that any function writes to (storage timber:x key)
  * a scheduled function (schedule function) that uninstall doesn't clear with schedule clear. A schedule can't be looked
    at from a function, so that one is compared with the code of uninstall.mcfunction.
A new scoreboard, storage key or schedule that is added to the datapack and forgotten in uninstall makes the test fail.
"""
import os
import re
import sys

repo, dest = sys.argv[1], sys.argv[2]

# 101/ holds the overlay of the older pack formats, both are scanned
folders = [os.path.join(repo, "data", "timber", "function"), os.path.join(repo, "101", "data", "timber", "function")]
uninstall_text = ""
objectives, schedules, storage_keys = set(), set(), set()
for folder in folders:
    for root, _, files in os.walk(folder):
        for name in files:
            if not name.endswith(".mcfunction"):
                continue
            path = os.path.join(root, name)
            text = open(path, encoding="utf-8", errors="replace").read()
            if os.path.relpath(path, folder).replace(os.sep, "/") == "uninstall.mcfunction":
                uninstall_text += text + "\n"
                continue
            # a name that is a macro argument ($(obj)) is only known at runtime: the axes, they have their own check in the test
            objectives.update(n for n in re.findall(r"scoreboard objectives add (\S+)", text) if "$(" not in n)
            schedules.update(re.findall(r"schedule function (timber:[\w/]+)", text))
            # storage timber:settings dialog.inputs[0].initial -> (timber:settings, dialog), the top level key is what gets removed
            storage_keys.update(re.findall(r"storage (timber:\w+) (\w+)", text))

if not objectives:
    sys.exit("gen-uninstall-check: no 'scoreboard objectives add' found in " + str(folders) + ", is the path right?")

out = os.path.join(dest, "data", "timber_test", "function", "generated")
os.makedirs(out, exist_ok=True)


def write(name, lines):
    with open(os.path.join(out, name), "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


HEADER = "#> GENERATED by .github/scripts/gen-uninstall-check.py from the code of the datapack, do not edit."

# --- before the uninstall: something in every storage key
# The first line of both functions sets a marker that the test checks: PackTest doesn't complain about a function that doesn't
# exist, without the marker a missing or broken generation step would leave a test that checks nothing and passes.
write("uninstall_prepare.mcfunction", [HEADER, "#> Puts a value into every storage key the datapack writes to and that is empty.",
                                       "scoreboard objectives add timber_test dummy", "scoreboard players set #uninstall_prepare_ran timber_test 1"]
      # only where there is nothing yet: a key that holds real data (the list of axes) must stay usable for the uninstall
      + [f"execute unless data storage {sid} {key} run data modify storage {sid} {key} set value 1" for sid, key in sorted(storage_keys)])

# --- after the uninstall
lines = [
    HEADER,
    "#> Fails if anything of the datapack is left after timber:uninstall, the names are in the message.",
    "scoreboard objectives add timber_test dummy",
    "scoreboard players set #uninstall_check_ran timber_test 1",
    "data modify storage timber_test:uninstall left set value []",
]
for name in sorted(objectives):
    # adding 0 to a holder works when the objective exists and fails when it doesn't.
    # The names go into a list, a fail in the loop would end this function at the first one.
    lines += [
        f"execute store success score #exists timber_test run scoreboard players add #uninstall_probe {name} 0",
        f'execute if score #exists timber_test matches 1 run data modify storage timber_test:uninstall left append value "scoreboard {name}"',
        f"execute if score #exists timber_test matches 1 run scoreboard players reset #uninstall_probe {name}",
    ]
for sid, key in sorted(storage_keys):
    # data get fails when the key is not there
    lines += [
        f"execute store success score #exists timber_test run data get storage {sid} {key}",
        f'execute if score #exists timber_test matches 1 run data modify storage timber_test:uninstall left append value "storage {sid} {key}"',
    ]
cleared_schedules = set(re.findall(r"schedule clear (timber:[\w/]+)", uninstall_text))
for target in sorted(schedules - cleared_schedules):
    lines.append(f'data modify storage timber_test:uninstall left append value "schedule {target} (not cleared in uninstall.mcfunction)"')

lines.append('execute if data storage timber_test:uninstall left[0] run fail [{"text":"left after uninstall: "},{"nbt":"left","storage":"timber_test:uninstall"}]')
lines.append("# (no assert after the fail: it would replace the message with an \"Expected ...\" without the names)")
write("uninstall_objectives.mcfunction", lines)

print(f"gen-uninstall-check: {len(objectives)} objectives, {len(storage_keys)} storage keys, {len(schedules)} schedules "
      f"({len(schedules - cleared_schedules)} not cleared by uninstall)")
